apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: NAME
  region: REGION
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    labels: { node-role.kubernetes.io/system: system }
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    ssh:
      publicKeyPath: id_rsa.pub
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 3
    minSize: 1
    maxSize: 6
    labels: { node-role.kubernetes.io/worker: worker }
    ssh:
      publicKeyPath: id_rsa.pub
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
secretsEncryption:
  keyARN: "KEY"

iam:
  withOIDC: true